spring.application.name=TrabalhoIndividual

spring.datasource.url=jdbc:postgresql://localhost:5432/concessionaria
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.versao=1.0.0